[tool.poetry]
name = "visualizations"
version = "0.1.0"
description = ""
authors = ["Molly Jones <mojones.e@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
easytkinter = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
